apiVersion: v1
kind: Pod
metadata:
  name: webapp
spec:
  containers:
    - name: nginx-container
      image: nginx
      volumeMounts:
        - mountPath: /var/log/nginx
          name: storage
  volumes:
    - name: storage
      persistentVolumeClaim:
        claimName: claim-log-1
